### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by iandouglas** [Kathybui732/viewing_party#18]
As a user, 
After authenticating,
I should be redirected to the dashboard page, 
Where I should see: 
- [x] 'Welcome `<username>`!' at the top of page
- [ ] #17  A button to Discover Movies
- [ ] #16 A friends section
- [ ] #15 A viewing parties section

**Comment by ajtran303** [comment]
I think the strategy would be to:

- Make the Discover movies button, with the proper link to the discover page

- Create two `<section>` tags, with attributes `class="friends"` and `class="viewing_parties"`
- Then we can test the sections to have_text `"Friends"` and `"Viewing Parties"`
